application: sympo-score
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /
  static_files: static/index.html
  upload: static/index\.html

- url: /favicon\.ico
  static_files: static/favicon.ico
  upload: static/favicon\.ico

- url: /scripts
  static_dir: static/scripts

- url: /styles
  static_dir: static/styles

- url: /partials
  static_dir: static/partials

- url: /api/admin/.*
  script: main.app
  login: admin
  auth_fail_action: unauthorized

- url: /api/.*
  script: main.app

libraries:
- name: webapp2
  version: "2.5.2"
